#!/usr/bin/env python3
import argparse
import requests

my_parser = argparse.ArgumentParser(description='returns the amount of money each visiting operator owes \
    to a specific operator in a period, with operator id and period provided in the params of the url')
my_parser.add_argument('--op1', metavar='operator_id', type=str, required=True,
                        help='select the station operator')
my_parser.add_argument('--datefrom', metavar='YYYYMMDD', type=str, required=True,
                        help='select the starting date')
my_parser.add_argument('--dateto', metavar='YYYYMMDD', type=str, required=True,
                        help='select the ending date')
my_parser.add_argument('--format', metavar='{json|csv}', type=str, required=True,
                        help='select the format type of the output (json or csv)')
args = my_parser.parse_args()

try:    
    url = 'http://127.0.0.1:9103/ChargesBy/' + args.op1 + '/' + args.datefrom + '/' + args.dateto + '?format=' + args.format
    r = requests.get(url)
    r.raise_for_status()
    try:    
        if args.format == 'json':
            print(r.json())
        elif args.format == 'csv': 
            print(r.text)
    except Exception as e:
        print(e)
except Exception as e:
    print(e)