#!/usr/bin/env python3
import argparse
import requests

my_parser = argparse.ArgumentParser(description='checks if there is connection with database')
args = my_parser.parse_args()

try:   
    r = requests.get('http://127.0.0.1:9103/admin/healthcheck')
    try:
        print(r.json())
    except Exception as e:
        print(e)
    r.raise_for_status()
except Exception as e:
    print(e)