#!/usr/bin/env python3
import argparse
import requests

my_parser = argparse.ArgumentParser(description='initializes pass collection in database')
args = my_parser.parse_args()

try:
    r = requests.post('http://127.0.0.1:9103/admin/resetpasses')
    try:
        print(r.json())
    except Exception as e:
        print(e)
    r.raise_for_status()
except Exception as e:
    print(e)